insert into exchange_rates(base_currency_id, target_currency_id, rate) values(1, 2, 0.011);
insert into exchange_rates(base_currency_id, target_currency_id, rate) values(1, 3, 0.011);
insert into exchange_rates(base_currency_id, target_currency_id, rate) values(2, 1, 89.75);
insert into exchange_rates(base_currency_id, target_currency_id, rate) values(2, 3, 0.95);
insert into exchange_rates(base_currency_id, target_currency_id, rate) values(3, 1, 94.62);
insert into exchange_rates(base_currency_id, target_currency_id, rate) values(3, 2, 1.05);
insert into exchange_rates(base_currency_id, target_currency_id, rate) values(2, 4, 3.27);
insert into exchange_rates(base_currency_id, target_currency_id, rate) values(2, 6, 1.44);
insert into exchange_rates(base_currency_id, target_currency_id, rate) values(4, 5, 2.21);